# Generated by Django 6.1 on 2026-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accouchement',
            name='manoeuvre_obstetricale',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes : forceps, ventouse, extraction_manuelle, autre, aucune', null=True, verbose_name='Manœuvre obstétricale'),
        ),
    ]
