# Generated by Django 6.1 on 2026-08-14 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_accouchement_manoeuvre_obstetricale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenPhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Date et heure de l'examen")),
                ('examine_par', models.CharField(blank=True, max_length=120, null=True, verbose_name='Examiné par')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('frequence_respiratoire', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fréquence respiratoire (cpm)')),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)')),
                ('tension_arterielle', models.CharField(blank=True, help_text='Exemple : 100/60', max_length=30, null=True, verbose_name='Tension artérielle')),
                ('saturation_oxygene', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO₂ (%)')),
                ('signes_generaux', models.JSONField(blank=True, default=list, help_text='Liste de codes : asthenie, fievre, paleur, cyanose, ictere, etc.', verbose_name='Signes généraux')),
                ('signes_fonctionnels', models.JSONField(blank=True, default=list, help_text='Liste de codes : dyspnee, toux, douleur, vomissements, diarrhee, etc.', verbose_name='Signes fonctionnels')),
                ('donnees_appareils', models.JSONField(blank=True, default=dict, help_text='Structure JSON prévue pour recevoir les examens par appareil : pleuropulmonaire, cardiovasculaire, digestif, neurologique, ORL, cutaneomuqueux, genitaux, osteoarticulaire.', verbose_name='Examen par appareil')),
                ('exceptions', models.TextField(blank=True, null=True, verbose_name='Exceptions / Imprévus')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_physiques', to='patient.observationmedicale', verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Examen physique de suivi',
                'verbose_name_plural': 'Examens physiques de suivi',
                'ordering': ['-date_heure'],
                'indexes': [models.Index(fields=['observation', '-date_heure'], name='patient_exa_observa_fcabb8_idx')],
            },
        ),
    ]
