# Generated by Django 6.1 on 2026-08-14 15:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_examenphysique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheRehydratation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('heure_debut', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Heure de début')),
                ('heure_fin', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('poids_initial_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Poids initial (kg)')),
                ('poids_final_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Poids final (kg)')),
                ('quantite_liquide_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité de liquide (mL)')),
                ('duree_minutes', models.PositiveIntegerField(blank=True, help_text='Si vide, la durée peut être calculée entre heure de début et heure de fin.', null=True, verbose_name='Durée (minutes)')),
                ('signes_generaux', models.JSONField(blank=True, default=list, help_text='Liste de codes : asthenie, fievre, paleur, cyanose, agitation, lethargie, etc.', verbose_name='Signes généraux')),
                ('signes_fonctionnels', models.JSONField(blank=True, default=list, help_text='Liste de codes : dyspnee, douleur, vomissements, diarrhee, oligurie, etc.', verbose_name='Signes fonctionnels')),
                ('etat_yeux', models.CharField(blank=True, choices=[('enfonce', 'Enfoncé'), ('cerne', 'Cerné'), ('normal', 'Normal')], max_length=30, null=True, verbose_name='État des yeux')),
                ('etat_muqueuses', models.CharField(blank=True, choices=[('seche', 'Sèche'), ('peu_humide', 'Peu humide'), ('humide', 'Humide')], max_length=30, null=True, verbose_name='État des muqueuses')),
                ('pli_cutane', models.CharField(blank=True, choices=[('persistant', 'Persistant'), ('efface_lentement', "S'efface lentement"), ('efface_rapidement', "S'efface rapidement"), ('pas_pli', 'Pas de pli cutané')], max_length=30, null=True, verbose_name='Pli cutané')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_rehydratation', to='patient.observationmedicale', verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Fiche de réhydratation',
                'verbose_name_plural': 'Fiches de réhydratation',
                'ordering': ['-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationHoraireRehydratation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_evaluation', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Heure d'évaluation")),
                ('signes_generaux', models.JSONField(blank=True, default=list, help_text='Liste de codes : asthenie, fievre, paleur, agitation, lethargie, convulsions, etc.', verbose_name='Signes généraux')),
                ('signes_fonctionnels', models.JSONField(blank=True, default=list, help_text='Liste de codes : dyspnee, douleur, vomissements, diarrhee, oligurie, anurie, etc.', verbose_name='Signes fonctionnels')),
                ('etat_yeux', models.CharField(blank=True, choices=[('enfonce', 'Enfoncé'), ('cerne', 'Cerné'), ('normal', 'Normal')], max_length=30, null=True, verbose_name='État des yeux')),
                ('etat_muqueuses', models.CharField(blank=True, choices=[('seche', 'Sèche'), ('peu_humide', 'Peu humide'), ('humide', 'Humide')], max_length=30, null=True, verbose_name='État des muqueuses')),
                ('pli_cutane', models.CharField(blank=True, choices=[('persistant', 'Persistant'), ('efface_lentement', "S'efface lentement"), ('efface_rapidement', "S'efface rapidement"), ('pas_pli', 'Pas de pli cutané')], max_length=30, null=True, verbose_name='Pli cutané')),
                ('urine', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10, null=True, verbose_name='Urine')),
                ('selles', models.CharField(blank=True, choices=[('absente', 'Absente'), ('presente', 'Présente'), ('diarrhee', 'Diarrhée'), ('glaires', 'Glaires'), ('sang', 'Sang')], max_length=30, null=True, verbose_name='Selles')),
                ('vomissements', models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Présent')], max_length=30, null=True, verbose_name='Vomissements')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('frequence_respiratoire', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fréquence respiratoire (cpm)')),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiche_rehydratation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_horaires', to='patient.ficherehydratation', verbose_name='Fiche de réhydratation')),
            ],
            options={
                'verbose_name': 'Évaluation horaire de réhydratation',
                'verbose_name_plural': 'Évaluations horaires de réhydratation',
                'ordering': ['heure_evaluation'],
            },
        ),
        migrations.AddIndex(
            model_name='ficherehydratation',
            index=models.Index(fields=['observation', '-heure_debut'], name='patient_fic_observa_eff116_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationhorairerehydratation',
            index=models.Index(fields=['fiche_rehydratation', 'heure_evaluation'], name='patient_eva_fiche_r_e87c54_idx'),
        ),
    ]
