# Generated by Django 6.1 on 2026-08-14 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_ficherehydratation_evaluationhorairerehydratation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitementAjustement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='Version')),
                ('date_heure', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('type_ajustement', models.CharField(choices=[('initial', 'Initial'), ('ajustement', 'Ajustement'), ('renouvellement', 'Renouvellement'), ('suspension', 'Suspension'), ('arret', 'Arrêt')], default='ajustement', max_length=30, verbose_name="Type d'ajustement")),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements_ajustes', to='patient.observationmedicale', verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Ajustement de traitement',
                'verbose_name_plural': 'Ajustements de traitement',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='LigneTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('medicament', 'Médicament'), ('soin', 'Soin'), ('autre', 'Autre')], default='medicament', max_length=20, verbose_name='Type de ligne')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom / Médicament / Soin')),
                ('dose', models.CharField(blank=True, help_text='Exemple : 500 mg, 10 mL, 1 g', max_length=120, null=True, verbose_name='Dose')),
                ('voie', models.CharField(blank=True, choices=[('orale', 'Orale'), ('iv_directe', 'IV directe'), ('perfusion', 'Perfusion'), ('im', 'IM'), ('sc', 'SC'), ('inhalation', 'Inhalation'), ('rectale', 'Rectale'), ('topique', 'Topique'), ('ophtalmique', 'Ophtalmique'), ('auriculaire', 'Auriculaire'), ('nasale', 'Nasale'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Voie')),
                ('frequence', models.CharField(blank=True, choices=[('dose_unique', 'Dose unique'), ('1_fois_jour', '1 fois/jour'), ('2_fois_jour', '2 fois/jour'), ('3_fois_jour', '3 fois/jour'), ('4_fois_jour', '4 fois/jour'), ('toutes_4_heures', 'Toutes les 4 heures'), ('toutes_6_heures', 'Toutes les 6 heures'), ('toutes_8_heures', 'Toutes les 8 heures'), ('toutes_12_heures', 'Toutes les 12 heures'), ('selon_besoin', 'Selon besoin'), ('continu', 'Continu'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Fréquence')),
                ('duree', models.CharField(blank=True, help_text='Exemple : 5 jours, 48 heures', max_length=120, null=True, verbose_name='Durée')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajustement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='patient.traitementajustement', verbose_name='Ajustement')),
            ],
            options={
                'verbose_name': 'Ligne de traitement',
                'verbose_name_plural': 'Lignes de traitement',
                'ordering': ['nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='traitementajustement',
            constraint=models.UniqueConstraint(fields=('observation', 'version'), name='unique_version_traitement_ajustement_par_observation'),
        ),
    ]
