# Generated by Django 6.1 on 2026-08-16 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_traitementajustement_lignetraitement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenclinique',
            name='pb_cm',
        ),
        migrations.RemoveField(
            model_name='examenclinique',
            name='pbd_cm',
        ),
        migrations.RemoveField(
            model_name='examenclinique',
            name='pbg_cm',
        ),
        migrations.RemoveField(
            model_name='ficherehydratation',
            name='duree_minutes',
        ),
        migrations.AddField(
            model_name='evaluationhorairerehydratation',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure'),
        ),
        migrations.AddField(
            model_name='examenclinique',
            name='pb_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='PB (mm)'),
        ),
        migrations.AddField(
            model_name='examenclinique',
            name='pbd_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='PB droit (mm)'),
        ),
        migrations.AddField(
            model_name='examenclinique',
            name='pbg_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='PB gauche (mm)'),
        ),
        migrations.AddField(
            model_name='examenphysique',
            name='glycelie',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Glycémie capillaire (g/l)'),
        ),
        migrations.AddField(
            model_name='ficherehydratation',
            name='duree_heure',
            field=models.PositiveIntegerField(blank=True, help_text='Si vide, la durée peut être calculée entre heure de début et heure de fin.', null=True, verbose_name='Durée (heure)'),
        ),
        migrations.AlterField(
            model_name='evaluationhorairerehydratation',
            name='signes_generaux',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes : asthenie, fievre, lethargie, etc.', verbose_name='Signes généraux'),
        ),
        migrations.AlterField(
            model_name='examenclinique',
            name='p_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='P/A (poids pour aâge)'),
        ),
        migrations.AlterField(
            model_name='examenclinique',
            name='p_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='P/T (poids pour taille)'),
        ),
        migrations.AlterField(
            model_name='examenclinique',
            name='t_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='T/A (taille pour âge)'),
        ),
        migrations.AlterField(
            model_name='examenphysique',
            name='signes_generaux',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes : asthenie, fievre, amaigrissement, anorexie, sueur profuse', verbose_name='Signes généraux'),
        ),
        migrations.AlterField(
            model_name='examenphysique',
            name='tension_arterielle',
            field=models.CharField(blank=True, help_text='Exemple : 100/60', max_length=30, null=True, verbose_name='Tension artérielle mmHg'),
        ),
        migrations.AlterField(
            model_name='ficherehydratation',
            name='signes_generaux',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes : asthenie, fievre, lethargie, etc.', verbose_name='Signes généraux'),
        ),
        migrations.AlterField(
            model_name='traitementajustement',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Ajustement N°'),
        ),
    ]
