# Generated by Django 4.2.30 on 2026-08-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_examenclinique_pb_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenParaclinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('imagerie', 'Imagerie'), ('biologie', 'Biologie'), ('fonctionnel', 'Examen fonctionnel'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'examen")),
                ('nom_examen', models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name="Nom de l'examen")),
                ('nom_examen_autre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre (préciser)')),
                ('date_examen', models.DateField(blank=True, null=True, verbose_name="Date de l'examen")),
                ('date_resultat', models.DateField(blank=True, null=True, verbose_name='Date du résultat')),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('en_cours', 'En cours'), ('resultat_disponible', 'Résultat disponible'), ('interprete', 'Interprété')], default='demande', max_length=30, verbose_name='Statut')),
                ('resultat', models.TextField(blank=True, help_text='Valeurs, mesures, observations...', null=True, verbose_name='Résultat')),
                ('fichier_resultat', models.FileField(blank=True, help_text='PDF, image, ou autre fichier du résultat', null=True, upload_to='examens_paracliniques/', verbose_name='Fichier du résultat')),
                ('interpretation', models.TextField(blank=True, null=True, verbose_name='Interprétation')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_paracliniques', to='patient.observationmedicale', verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Examen paraclinique',
                'verbose_name_plural': 'Examens paracliniques',
                'ordering': ['-date_examen', '-created_at'],
            },
        ),
    ]
