# Generated by Django 4.2.30 on 2026-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_examenparaclinique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenparaclinique',
            name='nom_examen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'examen"),
        ),
    ]
