# Generated by Django 4.2.30 on 2026-08-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_examenparaclinique_nom_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developpementpsychomoteur',
            name='langage',
            field=models.TextField(blank=True, default="\nEmission des sons gutturaux à 1-2 mois ; \ngazouillement à 3-4 mois ; \nbabillage à 5-6 mois ; \nsyllabes à 7-8 mois ; \ncomprends ce qu'on lui dit à 13-18 mois ; \nphrase complète à 24 mois et pose des questions à 36 mois\n", null=True, verbose_name='Langage'),
        ),
        migrations.AlterField(
            model_name='developpementpsychomoteur',
            name='motricite',
            field=models.TextField(blank=True, default="\nReflexes archaïques et marche automatique à 1 mois; \ntient sa tête, roule sur le côté à 3-4 mois ; \ntient assis avec soutient, appui sur ses mains, roule sur le ventre et dos à 5-6 mois ; \ntient assis seul, joue avec ses pieds à 7-8 mois ; \ndéplace à 4 pattes, tient debout à 9-10 mois ; \npousse l'objet avant lui à 11-12 mois ; \nmarche, monte des escaliers à 13-18 mois ; \ncourrir, sauter 24\n", null=True, verbose_name='Motricité'),
        ),
        migrations.AlterField(
            model_name='developpementpsychomoteur',
            name='prehension',
            field=models.TextField(blank=True, default="\nreflexe d'agrippement à 1 mois ; \npréhension en contact à 3-4 mois ; \npréhension volontaire et porte des objets dans la bouche à 5-6 mois; \nrelache un objet à la main volontaire et préhesion en pince inférieure à 7-8 mois ; \npréhension en pince supérieure à 9-10 mois ; \ntend ses jouets, pointe l'index à 11-12 mois ; \njeter, tient la cuillère à 13-18 mois ; \ntourner les pages du livre, tient parfaitement la cuillère à 24 mois\n", null=True, verbose_name='Préhension'),
        ),
        migrations.AlterField(
            model_name='developpementpsychomoteur',
            name='relationnelle',
            field=models.TextField(blank=True, default="\npleur, reconnaît la voix de sa mère à 1-2 mois ; \ncri, reconnait le visage de la familier à 3-4 mois ; \nmontre de l'intérêt pour les objets à 6-7 mois ; \nimite les gestes et les expressions faciales à 8-9 mois ; \ndéveloppe une relation affective avec les soignants à 10-12 mois\n", null=True, verbose_name='Relationnelle'),
        ),
    ]
