# Generated by Django 4.2.30 on 2026-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_developpementpsychomoteur_langage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationmedicale',
            name='numero_dossier',
        ),
        migrations.AlterField(
            model_name='observationmedicale',
            name='prenoms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom(s)'),
        ),
    ]
