# Generated by Django 4.2.30 on 2026-08-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_remove_observationmedicale_numero_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accouchement',
            name='poids_naissance_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Poids de naissance (g)'),
        ),
    ]
